### ISSUE TITLE
Demo improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#1]
Layout options:
- [x] ~~1. Changing options such as node spacing and edge length did not have an effect on resulting layout with CoLa~~
- [x] ~~2. Set padding to be 300, node spacing to be 30 with CiSE, and the resulting image is empty. I think setting the padding to be high is a problem for most/all layouts~~
 
Image options:
- [x] 11. There should have an option for no background
- [x] 12. Width, Height should not be allowed to be negative or zero (set to the default value when non-positive?)
- [x] 13. Some way to set all to the default would be nice (a Default button?)

UI:
- [x] ~~21. When layout is applied, while the spinner is spinning, can we perhaps write "Calculating..." on the button?~~

**Comment by hasanbalci** [comment]
@ugurdogrusoz I updated deployment. 

For 1, I can see difference when edge length and node spacing are changed especially on graphml sample. You can recheck it.

For 2, I don't see empty image but a small one in the middle, which is normal with given options. I think, we can expect users to use close values to default padding.

For 11, I added a "transparent" option for background color. I updated related part in README, as well.

For 12, user now cannot enter negative value for width and height from user interface. I also add a check for those options. If width and height values are less than or equal to zero, we set those values to default ones.

For 13, maybe we can add a small button near the Image Settings title to set image options to default values. Because each separate layout option has its own default button. 

For 21, currently the library I used for UI doesn't allow a text near the loading icon (there is an issue about this in their repo), but I will try to find a workaround.

**Comment by ugurdogrusoz** [comment]
13 let's do it like that; maybe with [this icon](https://www.flaticon.com/free-icon/settings_503851) with a tooltip "Reset defaults", right justified in the same row as "Image Settings".

21 don't spend much time on this, no big deal

**Comment by hasanbalci** [comment]
13 is done.

**Comment by hasanbalci** [comment]
I used same style for JSON/Image download icons and "Reset to default" icon. Now when we hover on them, background color changes. I also changed "About" color to orange. I think we can skip 21.
