### ISSUE TITLE
Local deployment issues

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/syblars#16]
To ease the deployment of the tool locally, we can make the following improvements:
- Provide a docker file
- Specify the versions of the tools used for installing/deploying (e.g. npm and node)
- Provide exemplary curl commands

**Comment by hasanbalci** [comment]
I added a Dockerfile to the root directory of the repository and wrote the instructions on how to use it in README. Dockerfile currently works only in Linux and Windows operating systems and **does not** work in macOS because of the Puppeteer related issues. 

I also added recommended Node.js and npm versions that can be used during the deployment of the service as a note in README.

Finally, I detailed the existing curl and fetch API example in README with real data to make it more understandable.
